const KB={
about:`Sur Sanjeevani Trust is a private charitable trust. The Trust Deed describes objects centred on evidence-based music therapy, interdisciplinary research, education, healthcare, psychological well-being, Indian music traditions and social transformation.\n\nRegistered Office: 96, Shri Ram Bhavan, Bhitti Ramnagar, Varanasi – 221008.`,
therapy:`The Trust Deed specifically includes evidence-based music therapy and interdisciplinary work involving psychology, social work, medical sciences, health sciences, neuroscience, yoga, music, Indian knowledge systems and education. It also includes therapeutic interventions, outreach and community-based programmes.`,
research:`Research is a central stated object. The deed provides for interdisciplinary research, research centres/laboratories, documentation, publications, databases, libraries, research projects, collaborations and dissemination of knowledge.`,
education:`The deed provides for diploma, degree, continuing education, faculty development, internships, fellowships and professional training programmes, as well as seminars, conferences, workshops and lectures and national/international collaborations.`,
journal:`The Trust Deed permits preparation and publication of books, materials, periodicals and other literature needed for its objectives, including educational and scientific publications.\n\nImportant: ISSN, editorial board, submission rules, fees and publication schedule should be displayed only after official confirmation.`,
volunteer:`The Trust's stated objects include community outreach, awareness campaigns, charitable activities and collaboration with organisations and agencies. Please contact the Trust to confirm current volunteer or collaboration opportunities.`,
donate:`The deed permits the Trust to receive donations, grants, contributions, CSR funding, fellowships and other lawful support for its charitable objects. Please contact the Trust for current donation instructions.`,
contact:`Sur Sanjeevani Trust\n96, Shri Ram Bhavan, Bhitti Ramnagar, Varanasi – 221008, India\nPhone: 8739031035 / 8400531957\nEmail: sursanjeevnitrust@gmail.com`,
vision:`Vision: To become a globally recognized centre of excellence integrating music, science, psychology, healthcare and Indian knowledge traditions for holistic well-being, research, education and social transformation.`,
mission:`Mission: To advance evidence-based music therapy, interdisciplinary research, innovation, consultancy and community service through ethical practice, scientific inquiry and multidisciplinary partnerships, improving health, well-being and quality of life.`
};
const labels={about:"About the Trust",therapy:"Music Therapy",research:"Research",education:"Training & Education",journal:"IJIMT Journal",volunteer:"Volunteer / Collaborate",donate:"Donate / Support",contact:"Contact",vision:"Vision",mission:"Mission"};
const quick=[["About","about"],["Music Therapy","therapy"],["Research","research"],["Training","education"],["IJIMT","journal"],["Volunteer","volunteer"],["Support","donate"],["Contact","contact"]];
const chat=document.getElementById("chat"),messages=document.getElementById("messages"),quickBox=document.getElementById("quick"),input=document.getElementById("input");
function add(text,type){const d=document.createElement("div");d.className="msg "+type;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function renderQuick(){quickBox.innerHTML="";quick.forEach(([label,key])=>{const b=document.createElement("button");b.textContent=label;b.onclick=()=>answer(key);quickBox.appendChild(b)})}
function openChat(topic){chat.classList.add("open");if(!messages.children.length){add("🙏 Namaste! Welcome to the Sur Sanjeevani AI Assistant.\n\nI can provide information about the Trust, music therapy, research, training, IJIMT, volunteering, support and contact details.\n\nHow may I help you?","bot");renderQuick()}if(topic)answer(topic)}
function closeChat(){chat.classList.remove("open")}
function answer(key){const text=KB[key];add(labels[key]||key,"user");add(text||fallback(key),"bot")}
function fallback(q){const s=String(q).toLowerCase();const map={music:"therapy",therapy:"therapy",trust:"about",about:"about",research:"research",training:"education",course:"education",education:"education",journal:"journal",ijimt:"journal",volunteer:"volunteer",collaborat:"volunteer",donat:"donate",support:"donate",contact:"contact",address:"contact",phone:"contact",email:"contact",vision:"vision",mission:"mission"};for(const k in map)if(s.includes(k))return KB[map[k]];return "I can currently help with the Trust, music therapy, research, training and education, IJIMT, volunteering, support/donations, vision, mission and contact details. Please choose a topic above or ask a short question."}
function send(){const v=input.value.trim();if(!v)return;input.value="";const s=v.toLowerCase();let key=null;for(const k of Object.keys(KB)){if(s.includes(k)||s.includes(labels[k].toLowerCase())){key=k;break}}if(key)answer(key);else{add(v,"user");add(fallback(v),"bot")}}
document.getElementById("year").textContent=new Date().getFullYear();
